apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: org-archon

resources:
  - knowledgebase.yaml

labels:
  - pairs:
      app.kubernetes.io/part-of: archon-knowledge-base
    includeSelectors: true
    includeTemplates: true

generatorOptions:
  disableNameSuffixHash: true
